ALTER TABLE departments
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE dept_emp
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE dept_manager
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE employees
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE salaries
ADD COLUMN id SERIAL PRIMARY KEY;

ALTER TABLE titles
ADD COLUMN id SERIAL PRIMARY KEY;

